In [2]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.0 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [3]:
# Mengimpor pustaka google_play_scraper untuk mengakses ulasan dan informasi aplikasi dari Google Play Store.
from google_play_scraper import app, reviews, Sort, reviews_all

import pandas as pd # Pandas untuk manipulasi dan analisis data
pd.options.mode.chained_assignment = None # Menonaktifkan peringatan chaining
import numpy as np # NumPy untuk komputasi numerik
seed = 0
np.random.seed(seed) # Mengatur seed untuk reproduktibilitas
import matplotlib.pyplot as plt # Matplotlib untuk visualisasi data
import seaborn as sns # Seaborn untuk visualisasi data statistik, mengatur gaya visualisasi
from sklearn.metrics import accuracy_score

import datetime as dt # Manipulasi data waktu dan tanggal
import re # Modul untuk bekerja dengan ekspresi reguler
import string # Berisi konstanta string, seperti tanda baca
from nltk.tokenize import word_tokenize # Tokenisasi teks
from nltk.corpus import stopwords # Daftar kata-kata berhenti dalam teks

!pip install sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory # Stemming (penghilangan imbuhan kata) dalam bahasa Indonesia
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory # Menghapus kata-kata berhenti dalam bahasa Indonesia

from wordcloud import WordCloud # Membuat visualisasi berbentuk awan kata (word cloud) dari teks

import nltk # Import pustaka NLTK (Natural Language Toolkit).
nltk.download('punkt_tab') # Mengunduh dataset yang diperlukan untuk tokenisasi teks.
nltk.download('stopwords') # Mengunduh dataset yang berisi daftar kata-kata berhenti (stopwords) dalam berbagai bahasa.

Collecting sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 5.3 MB/s eta 0:00:00
Installing collected packages: sastrawi
Successfully installed sastrawi-1.0.1

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [4]:
# Mengimpor pustaka google_play_scraper untuk mengakses ulasan dan informasi aplikasi dari Google Play Store.
from google_play_scraper import app, reviews_all, Sort

# Mengambil semua ulasan dari aplikasi dengan ID 'com.maxstream' di Google Play Store.
# Proses scraping mungkin memerlukan beberapa saat tergantung pada jumlah ulasan yang ada.
scrapreview = reviews_all(
    'com.maxstream',          # ID aplikasi
    lang='id',             # Bahasa ulasan (default: 'en')
    country='id',          # Negara (default: 'us')
    sort=Sort.MOST_RELEVANT, # Urutan ulasan (default: Sort.MOST_RELEVANT)
    count=5000             # Jumlah maksimum ulasan yang ingin diambil
)

In [5]:
# Menyimpan ulasan dalam file CSV
import csv

with open('ulasan_aplikasi.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Review'])  # Menulis header kolom
    for review in scrapreview:
        writer.writerow([review['content']])  # Menulis konten ulasan ke dalam file CSV

In [6]:
app_reviews_df = pd.DataFrame(scrapreview)
app_reviews_df.shape
app_reviews_df.head()
app_reviews_df.to_csv('ulasan_aplikasi.csv', index=False)

# Membuat DataFrame dari hasil scrapreview
app_reviews_df = pd.DataFrame(scrapreview)

# Menghitung jumlah baris dan kolom dalam DataFrame
jumlah_ulasan, jumlah_kolom = app_reviews_df.shape

In [7]:
# Menampilkan lima baris pertama dari DataFrame app_reviews_df
app_reviews_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,bb244032-9316-414b-9300-05ee57d60344,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Minta tolong diperbaiki untuk masalah login, s...",1,1,4.2.0,2026-06-11 00:03:06,None,NaT,4.2.0
1,ed27cf27-d32f-4bd1-82e4-b8df27401aa1,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Saat sedang nonton Piala Dunia setiap beberapa...,1,1,4.2.0,2026-06-13 22:50:24,None,NaT,4.2.0
2,9ced2f68-dec1-4294-bbd1-a83df2339eed,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Rencananya mau beli paket MaxStream buat nonto...,3,0,4.2.0,2026-06-11 16:31:21,None,NaT,4.2.0
3,0c9a28ae-53e4-4c9f-9ce6-d89f04c4aa34,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Ini aplikasi paling membosankan dan paling men...,1,1,4.2.0,2026-06-14 02:38:40,None,NaT,4.2.0
4,23f65e03-8525-44f3-9491-e44198c9548f,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"sangat tidak nyaman, sesi expired sangat serin...",1,1,4.2.0,2026-06-12 17:58:11,None,NaT,4.2.0

In [8]:
# Menampilkan informasi tentang DataFrame app_reviews_df
app_reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69594 entries, 0 to 69593
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              69594 non-null  object
 1   userName              69594 non-null  object
 2   userImage             69594 non-null  object
 3   content               69594 non-null  object
 4   score                 69594 non-null  int64
 5   thumbsUpCount         69594 non-null  int64
 6   reviewCreatedVersion  46596 non-null  object
 7   at                    69594 non-null  datetime64[ns]
 8   replyContent          21203 non-null  object
 9   repliedAt             21203 non-null  datetime64[ns]
 10  appVersion            46596 non-null  object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 5.8+ MB

In [9]:
# Membuat DataFrame baru (clean_df) dengan menghapus baris yang memiliki nilai yang hilang (NaN) dari app_reviews_df
clean_df = app_reviews_df.dropna()

In [11]:
# Menghapus baris duplikat dari DataFrame clean_df
clean_df = clean_df.drop_duplicates()

# Menghitung jumlah baris dan kolom dalam DataFrame clean_df setelah menghapus duplikat
jumlah_ulasan_setelah_hapus_duplikat, jumlah_kolom_setelah_hapus_duplikat = clean_df.shape

In [12]:
import re
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

def cleaningText(text):
    text = re.sub(r'@[A-Za-z0-9]+', '', text) # menghapus mention
    text = re.sub(r'#[A-Za-z0-9]+', '', text) # menghapus hashtag
    text = re.sub(r'RT[\s]', '', text) # menghapus RT
    text = re.sub(r"http\S+", '', text) # menghapus link
    text = re.sub(r'[0-9]+', '', text) # menghapus angka
    text = re.sub(r'[^\w\s]', '', text) # menghapus karakter selain huruf dan angka

    text = text.replace('\n', ' ') # mengganti baris baru dengan spasi
    text = text.translate(str.maketrans('', '', string.punctuation)) # menghapus semua tanda baca
    text = text.strip(' ') # menghapus karakter spasi dari kiri dan kanan teks
    return text

def casefoldingText(text): # Mengubah semua karakter dalam teks menjadi huruf kecil
    text = text.lower()
    return text

def tokenizingText(text): # Memecah atau membagi string, teks menjadi daftar token
    text = word_tokenize(text)
    return text

def filteringText(text): # Menghapus stopwords dalam teks
    listStopwords = set(stopwords.words('indonesian'))
    listStopwords1 = set(stopwords.words('english'))
    listStopwords.update(listStopwords1)
    listStopwords.update(['iya','yaa','gak','nya','na','sih','ku',"di","ga","ya","gaa","loh","kah","woi","woii","woy"])
    filtered = []
    for txt in text:
        if txt not in listStopwords:
            filtered.append(txt)
    text = filtered
    return text

def stemmingText(text): # Mengurangi kata ke bentuk dasarnya yang menghilangkan imbuhan awalan dan akhiran atau ke akar kata
    # Membuat objek stemmer
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()

    # Memecah teks menjadi daftar kata
    words = text.split()

    # Menerapkan stemming pada setiap kata dalam daftar
    stemmed_words = [stemmer.stem(word) for word in words]

    # Menggabungkan kata-kata yang telah distem
    stemmed_text = ' '.join(stemmed_words)

    return stemmed_text

def toSentence(list_words): # Mengubah daftar kata menjadi kalimat
    sentence = ' '.join(word for word in list_words)
    return sentence

In [13]:
slangwords = {"@": "di", "abis": "habis", "wtb": "beli", "masi": "masih", "wts": "jual", "wtt": "tukar", "bgt": "banget", "maks": "maksimal"}
def fix_slangwords(text):
     words = text.split()
     fixed_words = []

     for word in words:
       if word.lower() in slangwords:
           fixed_words.append(slangwords[word.lower()])
       else:
           fixed_words.append(word)

     fixed_text = ' '.join(fixed_words)
     return fixed_text

In [14]:
# Membersihkan teks dan menyimpannya di kolom 'text_clean'
clean_df['text_clean'] = clean_df['content'].apply(cleaningText)

# Mengubah huruf dalam teks menjadi huruf kecil dan menyimpannya di 'text_casefoldingText'
clean_df['text_casefoldingText'] = clean_df['text_clean'].apply(casefoldingText)

# Mengganti kata-kata slang dengan kata-kata standar dan menyimpannya di 'text_slangwords'
clean_df['text_slangwords'] = clean_df['text_casefoldingText'].apply(fix_slangwords)

# Memecah teks menjadi token (kata-kata) dan menyimpannya di 'text_tokenizingText'
clean_df['text_tokenizingText'] = clean_df['text_slangwords'].apply(tokenizingText)

# Menghapus kata-kata stop (kata-kata umum) dan menyimpannya di 'text_stopword'
clean_df['text_stopword'] = clean_df['text_tokenizingText'].apply(filteringText)

# Menggabungkan token-token menjadi kalimat dan menyimpannya di 'text_akhir'
clean_df['text_akhir'] = clean_df['text_stopword'].apply(toSentence)

In [15]:
clean_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,text_clean,text_casefoldingText,text_slangwords,text_tokenizingText,text_stopword,text_akhir
225,7c5d697e-3b7b-4ae5-a90b-8ce8b851c554,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,ternyata HOAX. sudah beli paket tapi server be...,1,0,4.2.0,2026-06-13 23:17:18,"Hi, Ka Rian. Mohon maaf atas ketidaknyamanan y...",2018-07-23 20:16:40,4.2.0,ternyata HOAX sudah beli paket tapi server ber...,ternyata hoax sudah beli paket tapi server ber...,ternyata hoax sudah beli paket tapi server ber...,"[ternyata, hoax, sudah, beli, paket, tapi, ser...","[hoax, beli, paket, server, bermasalah]",hoax beli paket server bermasalah
254,cec72fe7-0010-4f83-acfe-499d792c3206,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Setiap saya buka aplikasi selalu force close/m...,1,17,1.5.0,2019-12-08 08:45:39,"Hi, Ka. Terima kasih telah menggunakan aplikas...",2018-09-14 04:31:38,1.5.0,Setiap saya buka aplikasi selalu force closemu...,setiap saya buka aplikasi selalu force closemu...,setiap saya buka aplikasi selalu force closemu...,"[setiap, saya, buka, aplikasi, selalu, force, ...","[buka, aplikasi, force, closemuncul, keteranga...",buka aplikasi force closemuncul keterangan sis...
261,7b150c06-ae96-4fb3-87b4-5648cfe73408,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"aplikasi tai,, pas gak ada pertandingan stream...",1,36,1.7.0,2020-06-21 22:29:02,"Hi Ka Alfian, terima kasih telah menggunakan M...",2018-07-20 19:21:04,1.7.0,aplikasi tai pas gak ada pertandingan streamin...,aplikasi tai pas gak ada pertandingan streamin...,aplikasi tai pas gak ada pertandingan streamin...,"[aplikasi, tai, pas, gak, ada, pertandingan, s...","[aplikasi, tai, pas, pertandingan, streaming, ...",aplikasi tai pas pertandingan streaming lancar...
306,fc4e71fa-281a-42b1-a3cf-c5f1bc3dcf5d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,App yang bagus untuk streaming anak kost yang ...,5,36,1.2.5,2018-10-23 16:01:52,"Hi, Ka Kusmara. Terima kasih telah menggunakan...",2018-10-31 01:03:56,1.2.5,App yang bagus untuk streaming anak kost yang ...,app yang bagus untuk streaming anak kost yang ...,app yang bagus untuk streaming anak kost yang ...,"[app, yang, bagus, untuk, streaming, anak, kos...","[app, bagus, streaming, anak, kost, tv, siaran...",app bagus streaming anak kost tv siaran tv lok...
316,55e2b657-f392-460a-b62c-df195435c707,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Aplikasinya bagus,Bisa Buat lihat siaran Bola ...",3,4,1.2.6,2018-11-07 03:04:23,"Hi, Ka. Terima kasih atas masukan dan sarannya...",2019-01-04 06:07:19,1.2.6,Aplikasinya bagusBisa Buat lihat siaran Bola J...,aplikasinya bagusbisa buat lihat siaran bola j...,aplikasinya bagusbisa buat lihat siaran bola j...,"[aplikasinya, bagusbisa, buat, lihat, siaran, ...","[aplikasinya, bagusbisa, lihat, siaran, bola, ...",aplikasinya bagusbisa lihat siaran bola stream...

In [16]:
import csv
import requests
from io import StringIO

# Membaca data kamus kata-kata positif dari GitHub
lexicon_positive = dict()

response = requests.get('https://raw.githubusercontent.com/angelmetanosaa/dataset/main/lexicon_positive.csv')
# Mengirim permintaan HTTP untuk mendapatkan file CSV dari GitHub

if response.status_code == 200:
    # Jika permintaan berhasil
    reader = csv.reader(StringIO(response.text), delimiter=',')
    # Membaca teks respons sebagai file CSV menggunakan pembaca CSV dengan pemisah koma

    for row in reader:
        # Mengulangi setiap baris dalam file CSV
        lexicon_positive[row[0]] = int(row[1])
        # Menambahkan kata-kata positif dan skornya ke dalam kamus lexicon_positive
else:
    print("Failed to fetch positive lexicon data")

# Membaca data kamus kata-kata negatif dari GitHub
lexicon_negative = dict()

response = requests.get('https://raw.githubusercontent.com/angelmetanosaa/dataset/main/lexicon_negative.csv')
# Mengirim permintaan HTTP untuk mendapatkan file CSV dari GitHub

if response.status_code == 200:
    # Jika permintaan berhasil
    reader = csv.reader(StringIO(response.text), delimiter=',')
    # Membaca teks respons sebagai file CSV menggunakan pembaca CSV dengan pemisah koma

    for row in reader:
        # Mengulangi setiap baris dalam file CSV
        lexicon_negative[row[0]] = int(row[1])
        # Menambahkan kata-kata negatif dan skornya dalam kamus lexicon_negative
else:
    print("Failed to fetch negative lexicon data")

In [17]:
# Fungsi untuk menentukan polaritas sentimen dari tweet

def sentiment_analysis_lexicon_indonesia(text):
    #for word in text:

    score = 0
    # Inisialisasi skor sentimen ke 0

    for word in text:
        # Mengulangi setiap kata dalam teks

        if (word in lexicon_positive):
            score = score + lexicon_positive[word]
            # Jika kata ada dalam kamus positif, tambahkan skornya ke skor sentimen

    for word in text:
        # Mengulangi setiap kata dalam teks (sekali lagi)

        if (word in lexicon_negative):
            score = score + lexicon_negative[word]
            # Jika kata ada dalam kamus negatif, kurangkan skornya dari skor sentimen

    polarity=''
    # Inisialisasi variabel polaritas

    if (score >= 0):
        polarity = 'positive'
        # Jika skor sentimen lebih besar atau sama dengan 0, maka polaritas adalah positif
    elif (score < 0):
        polarity = 'negative'
        # Jika skor sentimen kurang dari 0, maka polaritas adalah negatif

    # else:
    #     polarity = 'neutral'
    # Ini adalah bagian yang bisa digunakan untuk menentukan polaritas netral jika diperlukan

    return score, polarity
    # Mengembalikan skor sentimen dan polaritas teks

In [18]:
results = clean_df['text_stopword'].apply(sentiment_analysis_lexicon_indonesia)
results = list(zip(*results))
clean_df['polarity_score'] = results[0]
clean_df['polarity'] = results[1]
print(clean_df['polarity'].value_counts())

polarity
positive    8547
negative    5711
Name: count, dtype: int64

In [19]:
clean_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,text_clean,text_casefoldingText,text_slangwords,text_tokenizingText,text_stopword,text_akhir,polarity_score,polarity
225,7c5d697e-3b7b-4ae5-a90b-8ce8b851c554,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,ternyata HOAX. sudah beli paket tapi server be...,1,0,4.2.0,2026-06-13 23:17:18,"Hi, Ka Rian. Mohon maaf atas ketidaknyamanan y...",2018-07-23 20:16:40,4.2.0,ternyata HOAX sudah beli paket tapi server ber...,ternyata hoax sudah beli paket tapi server ber...,ternyata hoax sudah beli paket tapi server ber...,"[ternyata, hoax, sudah, beli, paket, tapi, ser...","[hoax, beli, paket, server, bermasalah]",hoax beli paket server bermasalah,-2,negative
254,cec72fe7-0010-4f83-acfe-499d792c3206,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Setiap saya buka aplikasi selalu force close/m...,1,17,1.5.0,2019-12-08 08:45:39,"Hi, Ka. Terima kasih telah menggunakan aplikas...",2018-09-14 04:31:38,1.5.0,Setiap saya buka aplikasi selalu force closemu...,setiap saya buka aplikasi selalu force closemu...,setiap saya buka aplikasi selalu force closemu...,"[setiap, saya, buka, aplikasi, selalu, force, ...","[buka, aplikasi, force, closemuncul, keteranga...",buka aplikasi force closemuncul keterangan sis...,-9,negative
261,7b150c06-ae96-4fb3-87b4-5648cfe73408,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"aplikasi tai,, pas gak ada pertandingan stream...",1,36,1.7.0,2020-06-21 22:29:02,"Hi Ka Alfian, terima kasih telah menggunakan M...",2018-07-20 19:21:04,1.7.0,aplikasi tai pas gak ada pertandingan streamin...,aplikasi tai pas gak ada pertandingan streamin...,aplikasi tai pas gak ada pertandingan streamin...,"[aplikasi, tai, pas, gak, ada, pertandingan, s...","[aplikasi, tai, pas, pertandingan, streaming, ...",aplikasi tai pas pertandingan streaming lancar...,-11,negative
306,fc4e71fa-281a-42b1-a3cf-c5f1bc3dcf5d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,App yang bagus untuk streaming anak kost yang ...,5,36,1.2.5,2018-10-23 16:01:52,"Hi, Ka Kusmara. Terima kasih telah menggunakan...",2018-10-31 01:03:56,1.2.5,App yang bagus untuk streaming anak kost yang ...,app yang bagus untuk streaming anak kost yang ...,app yang bagus untuk streaming anak kost yang ...,"[app, yang, bagus, untuk, streaming, anak, kos...","[app, bagus, streaming, anak, kost, tv, siaran...",app bagus streaming anak kost tv siaran tv lok...,-13,negative
316,55e2b657-f392-460a-b62c-df195435c707,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Aplikasinya bagus,Bisa Buat lihat siaran Bola ...",3,4,1.2.6,2018-11-07 03:04:23,"Hi, Ka. Terima kasih atas masukan dan sarannya...",2019-01-04 06:07:19,1.2.6,Aplikasinya bagusBisa Buat lihat siaran Bola J...,aplikasinya bagusbisa buat lihat siaran bola j...,aplikasinya bagusbisa buat lihat siaran bola j...,"[aplikasinya, bagusbisa, buat, lihat, siaran, ...","[aplikasinya, bagusbisa, lihat, siaran, bola, ...",aplikasinya bagusbisa lihat siaran bola stream...,6,positive

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

# Pisahkan data menjadi fitur (tweet) dan label (sentimen)
X = clean_df['text_akhir']
y = clean_df['polarity']

# Ekstraksi fitur dengan TF-IDF
tfidf = TfidfVectorizer(max_features=200, min_df=17, max_df=0.8 )
X_tfidf = tfidf.fit_transform(X)

# Konversi hasil ekstraksi fitur menjadi dataframe
features_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf.get_feature_names_out())

# Menampilkan hasil ekstraksi fitur
features_df

# Bagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)

In [24]:
from sklearn.naive_bayes import BernoulliNB

# Membuat objek model Naive Bayes (Bernoulli Naive Bayes)
naive_bayes = BernoulliNB()

# Melatih model Naive Bayes pada data pelatihan
naive_bayes.fit(X_train.toarray(), y_train)

# Prediksi sentimen pada data pelatihan dan data uji
y_pred_train_nb = naive_bayes.predict(X_train.toarray())
y_pred_test_nb = naive_bayes.predict(X_test.toarray())

# Evaluasi akurasi model Naive Bayes
accuracy_train_nb = accuracy_score(y_pred_train_nb, y_train)
accuracy_test_nb = accuracy_score(y_pred_test_nb, y_test)

# Menampilkan akurasi
print('Naive Bayes - accuracy_train:', accuracy_train_nb)
print('Naive Bayes - accuracy_test:', accuracy_test_nb)

Naive Bayes - accuracy_train: 0.8449938628791864
Naive Bayes - accuracy_test: 0.8499298737727911

In [25]:
from sklearn.ensemble import RandomForestClassifier

# Membuat objek model Random Forest
random_forest = RandomForestClassifier()

# Melatih model Random Forest pada data pelatihan
random_forest.fit(X_train.toarray(), y_train)

# Prediksi sentimen pada data pelatihan dan data uji
y_pred_train_rf = random_forest.predict(X_train.toarray())
y_pred_test_rf = random_forest.predict(X_test.toarray())

# Evaluasi akurasi model Random Forest
accuracy_train_rf = accuracy_score(y_pred_train_rf, y_train)
accuracy_test_rf = accuracy_score(y_pred_test_rf, y_test)

# Menampilkan akurasi
print('Random Forest - accuracy_train:', accuracy_train_rf)
print('Random Forest - accuracy_test:', accuracy_test_rf)

Random Forest - accuracy_train: 0.9691390496230055
Random Forest - accuracy_test: 0.8895511921458625

In [26]:
from sklearn.linear_model import LogisticRegression

# Membuat objek model Logistic Regression
logistic_regression = LogisticRegression()

# Melatih model Logistic Regression pada data pelatihan
logistic_regression.fit(X_train.toarray(), y_train)

# Prediksi sentimen pada data pelatihan dan data uji
y_pred_train_lr = logistic_regression.predict(X_train.toarray())
y_pred_test_lr = logistic_regression.predict(X_test.toarray())

# Evaluasi akurasi model Logistic Regression pada data pelatihan
accuracy_train_lr = accuracy_score(y_pred_train_lr, y_train)

# Evaluasi akurasi model Logistic Regression pada data uji
accuracy_test_lr = accuracy_score(y_pred_test_lr, y_test)

# Menampilkan akurasi
print('Logistic Regression - accuracy_train:', accuracy_train_lr)
print('Logistic Regression - accuracy_test:', accuracy_test_lr)

Logistic Regression - accuracy_train: 0.904436261616693
Logistic Regression - accuracy_test: 0.9081346423562412

In [27]:
from sklearn.tree import DecisionTreeClassifier

# Membuat objek model Decision Tree
decision_tree = DecisionTreeClassifier()

# Melatih model Decision Tree pada data pelatihan
decision_tree.fit(X_train.toarray(), y_train)

# Prediksi sentimen pada data pelatihan dan data uji
y_pred_train_dt = decision_tree.predict(X_train.toarray())
y_pred_test_dt = decision_tree.predict(X_test.toarray())

# Evaluasi akurasi model Decision Tree
accuracy_train_dt = accuracy_score(y_pred_train_dt, y_train)
accuracy_test_dt = accuracy_score(y_pred_test_dt, y_test)

# Menampilkan akurasi
print('Decision Tree - accuracy_train:', accuracy_train_dt)
print('Decision Tree - accuracy_test:', accuracy_test_dt)

Decision Tree - accuracy_train: 0.9691390496230055
Decision Tree - accuracy_test: 0.8639551192145862